---
title: "Laboratorio # 1"
author: "Francisco Areyuna"
date: "27-09-2025"
format: "html"
---

# Titulo 1

El propósito de este laboratorio es que cada estudiante presente al menos tres visualizaciones generadas a partir de un dataset de la página datos abiertos Ecuador. Estas visualizaciones deben ser construidas utilizando cualquier biblioteca de visualización en Python (por ejemplo, Altair, Matplotlib o Seaborn).  

## 1. Importación de dataset

https://datosabiertos.gob.ec/dataset/temperatura-maxima-absoluta/resource/8e27bed1-3c32-4f33-a51c-d75684097f50


```{python}

import altair as alt

import pandas as pd

df = pd.read_csv(r'C:\Users\usuar\Desktop\Yachay_Tech\2. Aprendizaje_Maquina\github\inamhi-temperaturamaxima-2019diciembre.csv', delimiter=';', encoding='latin-1')


dias_meses = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic']

df = df.melt(
    id_vars=['Estacion', 'NombreEstacion', 'longitud2', 'latitud2', 'altitud', 'anio'],
    value_vars=dias_meses,
    var_name='Mes',
    value_name='Temperatura_Maxima_C'
)


df['Temperatura_Maxima_C'] = (
    df['Temperatura_Maxima_C']
    .str.replace(',', '.', regex=False)
    .astype(float)
)


df.dropna(subset=['Temperatura_Maxima_C', 'latitud2', 'longitud2'], inplace=True)



```


## 2. Vizualización de las principales caracteristicas del dataset

```{python}
df.info()

```

## 3. Grafico de lineas

```{python}

orden_meses = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic']

alt.Chart(df).mark_line(point=True).encode(

    x=alt.X('Mes', sort=orden_meses), 
    

    y=alt.Y('mean(Temperatura_Maxima_C)', title='Temperatura Máx. Promedio (°C)'), 
    

    tooltip=['Mes', 'mean(Temperatura_Maxima_C)']
).properties(
    title='Temperatura Máxima Promedio Mensual (General)'
).interactive()

```

La grafica muestras que el mes de julio presenta la temperatura mas baja en el rango del dataset. Los meses de octubre, marzo y abril presentan las mayores temperaturas.

## 3. Grafico de barras

```{python}


alt.Chart(df).mark_bar().encode(

    x=alt.X('Mes', sort=orden_meses), 
    

    y=alt.Y('mean(Temperatura_Maxima_C)', title='Temperatura Máx. Promedio (°C)'), 
    

    color=alt.Color('mean(Temperatura_Maxima_C)', scale=alt.Scale(scheme='orangered')),
    
    tooltip=['Mes', 'mean(Temperatura_Maxima_C)']
).properties(
    title='Temperatura Máxima Promedio Mensual por Mes'
)

```


## 4. Grafico de histograma

```{python}



alt.Chart(df).mark_bar().encode(

    x=alt.X('Temperatura_Maxima_C', bin=alt.Bin(maxbins=25), title='Temperatura Máxima (°C)'),   
    y=alt.Y('count()', title='Frecuencia de Registros'),
    
    tooltip=['Temperatura_Maxima_C', 'count()']
).properties(
    title='Distribución General de la Temperatura Máxima (Todo el Año)'
)



```


## 5. Grafico de dispersión


```{python}


alt.Chart(df).mark_point(filled=True, opacity=0.8).encode(

    x=alt.X('altitud', title='Altitud (msnm)'), 
    

    y=alt.Y('mean(Temperatura_Maxima_C)', title='Temperatura Máxima Promedio (°C)'),
    

    color=alt.Color('Mes:N'),
    

    tooltip=['NombreEstacion', 'altitud', 'Temperatura_Maxima_C', 'Mes']
).properties(
    title='Temperatura Máxima Promedio vs. Altitud de las Estaciones'
).interactive() 
```

## Reflexion final:


La grafica muestras que el mes de julio presenta la temperatura mas baja en el rango del dataset. Los meses de octubre, marzo y abril presentan las mayores temperaturas.

Esto se visualiza en la grafica de lineas y barras.

El grafico de dispersión muestra una correlación negativa entre la temperatura maxima de cada estación y la altitud.

EL histograma muestra que la temperatura con mayor frecuencia es 24 y 33 °C.


```{python}

```


```{python}

```